using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using Photon.Pun;
using TMPro;

public class MenuController : MonoBehaviourPunCallbacks
{
    [SerializeField]private GameObject _waitMenu;
    //field for taking the name of room created.
    [SerializeField] TMP_InputField createRoomInputField;
    [SerializeField] TMP_InputField joinRoomInputField;


    //functions are publicly defined because they are
    //required to be invoked by members outside of the class.
    public void StartMultiplayer()
    {
        //MenuManager.instance.OpenMenu("loading");
        //connecting to the photon master server with the settings generated by photon.
        Debug.Log("Connecting to Master");

        PhotonNetwork.ConnectUsingSettings();

        _waitMenu.gameObject.SetActive(true);
    }

    
    //----------------------------------------Photon Callbacks--------------------------------------

    public override void OnConnectedToMaster()
    {
        Debug.Log("Connected to master");
        PhotonNetwork.JoinLobby();
    }

    public override void OnJoinedLobby()
    {
        Debug.Log("Joined lobby");
        _waitMenu.gameObject.SetActive(false);
    }

    public override void OnJoinedRoom()
    {
        PhotonNetwork.LoadLevel("Game");
    }




    //-------------------------------------------------------------------------------------------------
    public void PlayGame()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);
    }

    public void QuitGame()
    {
        Debug.Log("Quit!");
        Application.Quit();
    }

    public void CreateRoom()
    {
        PhotonNetwork.CreateRoom(createRoomInputField.text);
    }

    public void JoinRoom()
    {
        PhotonNetwork.JoinRoom(joinRoomInputField.text);
    }
}
